#-
run -b args
run -b chain
run params
run exit
run redir
#/

#args b!
echo Test 'basic command' "with textual" arguments
echo 'environment variables:' $HOME
echo 'globs:' ../src/*.rs
#/

#chain b
yes | head -n 2
#/

#params
FOO='bar' echo ${FOO-No foo}
FOO='bar' printenv FOO
FOO='bar'
echo ${FOO-No foo}
printenv FOO || :
export FOO
printenv FOO
#/

#exit r
run nonexistent-target 2>/dev/null || :
#/

#redir r!
echo 'hello' >> /dev/null
cat < ../.gitignore

cat << EOF
Heredoc
EOF
#/
