[package]
name = "runscript"
version = "1.0.0-beta.4"
description = "Project execution script manager"
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities", "development-tools::build-utils"]
repository = "https://github.com/TheOnlyMrCat/runscript"
authors = ["TheOnlyMrCat <skylifegame@gmail.com>"]
edition = "2021"

[[bin]]
name = "run"
path = "src/main.rs"

[features]
old-parser = []
dev-panic = []

[dependencies]
atty = "0.2"
clap = "3.1"
exitcode = "1.1"
glob = "0.3.0"
indexmap = "1.7"
itertools = "0.10.1"
os_info = "3.2"
serde = { version = "1.0.136", features = ["derive"] }
tempfile = "3.3.0"
termcolor = "1.1"
toml = "0.5.8"
uuid = { version = "0.8", features = ["v4"], default-features = false }

[target.'cfg(windows)'.dependencies]
winapi = "0.3"

[target.'cfg(unix)'.dependencies]
nix = "0.23"
