[package]
name = "runscript"
version = "1.0.1"
description = "Like make, but for running"
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities", "development-tools::build-utils"]
repository = "https://github.com/TheOnlyMrCat/runscript"
authors = ["TheOnlyMrCat <skylifegame@gmail.com>"]
edition = "2018"

[[bin]]
name = "run"
path = "src/main.rs"

[build-dependencies]
lalrpop = { version = "0.19.0", features = ["lexer"] } # LALR parser generator

[dependencies]
getopts = "0.2.21"           # Command-line option parsing
lalrpop-util = "0.19.0"      # LALRPOP Runtime
regex = "1"                  # Regex parsing, for LALRPOP's lexer
codespan-reporting = "0.9.5" # Formatted error messages
termcolor = "1.1.0"          # Terminal colouring
globwalk = "0.8.0"           # Glob parsing
