[package]
name = "runscript"
version = "2.0.0-alpha.1"
description = "Project execution script manager"
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities", "development-tools::build-utils"]
repository = "https://github.com/TheOnlyMrCat/runscript"
authors = ["TheOnlyMrCat <skylifegame@gmail.com>"]
edition = "2018"

[profile.release]
panic = "abort"

[[bin]]
name = "run"
path = "src/main.rs"

[lib]
name = "runscript"

[dependencies]
getopts = "0.2"
termcolor = "1.1"
filenamegen = "0.2"
anyhow = "1.0"
enum-map = "0.6"
atty = "0.2"
either = "1.6"
conch-parser = "0.1"
linked-hash-map = "0.5"
crossbeam-utils = "0.8"

trace = { version = "0.1", optional = true }
itertools = "0.10.1"
