[package]
name = "runscript"
version = "1.2.0-pre.2"
description = "Like make, but for running"
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities", "development-tools::build-utils"]
repository = "https://github.com/TheOnlyMrCat/runscript"
authors = ["TheOnlyMrCat <skylifegame@gmail.com>"]
edition = "2018"

[profile.release]
panic = "abort"

[[bin]]
name = "run"
path = "src/main.rs"

[dependencies]
getopts = "0.2"        # Command-line option parsing
termcolor = "1.1"      # Terminal colouring
filenamegen = "0.2"    # Glob parsing and walking
anyhow = "1.0"         # Trait-based error type
enum-map = "0.6"     # Array-based map over enum constants

trace = { version = "0.1", optional = true }