[package]
name = "runscript"
version = "0.1.0"
authors = ["TheOnlyMrCat <signupforforums5@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
lalrpop = { version = "0.19.0", features = ["lexer"] } # LALR parser generator

[dependencies]
getopts = "0.2.21"      # Option parsing
lalrpop-util = "0.19.0" # Util for LALRPOP
regex = "1"             # Regex parsing
