[package]
name = "runscript"
version = "2.0.0-alpha.2"
description = "Project execution script manager"
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities", "development-tools::build-utils"]
repository = "https://github.com/TheOnlyMrCat/runscript"
authors = ["TheOnlyMrCat <skylifegame@gmail.com>"]
edition = "2018"

[[bin]]
name = "run"
path = "main.rs"

[profile.release]
panic = "abort"

[dependencies]
getopts = "0.2"
termcolor = "1.1"
enum-map = "0.6"
atty = "0.2"
conch-parser = "0.1"
linked-hash-map = "0.5"
crossbeam-utils = "0.8"
itertools = "0.10.1"

trace = { version = "0.1", optional = true }
glob = "0.3.0"

[target.'cfg(unix)'.dependencies]
nix = "0.23"
