[package]
name = "runscript"
version = "0.6.0"
description = "Like make, but for running"
license = "MIT"
readme = "README.md"
repository = "https://github.com/TheOnlyMrCat/runscript"
authors = ["TheOnlyMrCat <skylifegame@gmail.com>"]
edition = "2018"

[[bin]]
name = "run"
path = "src/main.rs"

[build-dependencies]
lalrpop = { version = "0.19.0", features = ["lexer"] } # LALR parser generator

[dependencies]
getopts = "0.2.21"      # Option parsing
lalrpop-util = "0.19.0" # Util for LALRPOP
regex = "1"             # Regex parsing
