[package]
name = "runscript"
version = "2.0.0-alpha.2"
description = "Project execution script manager"
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities", "development-tools::build-utils"]
repository = "https://github.com/TheOnlyMrCat/runscript"
authors = ["TheOnlyMrCat <skylifegame@gmail.com>"]
edition = "2018"

[[bin]]
name = "run"
path = "src/main.rs"

[dependencies]
getopts = "0.2"
termcolor = "1.1"
enum-map = "0.6"
atty = "0.2"
conch-parser = "0.1"
linked-hash-map = "0.5"
itertools = "0.10.1"
glob = "0.3.0"
exitcode = "1.1"
config = { version = "0.11", features = ["toml"] }

# Panic handling
uuid = { version = "0.8", features = ["v4"], default-features = false }
os_info = { version = "3.0" }

trace = { version = "0.1", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = "0.3"

[target.'cfg(unix)'.dependencies]
nix = "0.23"
