[package]
name = "runscript-parse"
version = "0.1.0"
edition = "2021"

[lib]
name = "runscript_parse"

[[bin]]
name = "repl"
required-features = ["reedline"]

[dependencies]
chumsky = "0.8.0"
reedline = { version = "0.16.0", optional = true }

[dev-dependencies]
pretty_assertions = "1.3.0"
